<script lang="ts">
	import { goto } from '$app/navigation';
	import { clean, parse } from '$lib/format.js';
	import Markdown from '$lib/components/Markdown.svelte';
	export let data;

	$: explanation = data.explanation;
    $: answer = parse(explanation.trivium.answer);

	async function back() {
		await goto(`/trivia/${explanation.trivium.id}`);
	}

	async function next() {
		await goto(`/`);
	}
</script>

<div class="flex flex-col space-y-2 h-screen">
	<div class="text-m text-slate-600 text-center w-full py-2 dark:bg-blue-500">
		{clean(explanation.trivium.category)} - ${explanation.trivium.score}
	</div>
	<div class="text-sm text-slate-900 self-center px-2 pb-4">
        {#if answer.meta}
            <span class="text-slate-400 italic">{answer.meta}</span>&nbsp;
        {/if}
		<span>{answer.text}</span>:&nbsp;
		<span class="font-bold">{clean(explanation.trivium.question)}</span>
	</div>
	<div
		class="text-m text-slate-900 dark:text-white text-left overflow-y-auto p-4 border border-blue-300"
	>
		<div class="font-bold mb-2">Summary (generated by AI):</div><Markdown content={explanation.summary.content} />
	</div>
	<div class="!mt-auto w-full flex">
		<button
			on:click={back}
			class="bg-red-500 hover:bg-red-600 dark:text-white font-bold py-2 px-4 text-2xl basis-1/2"
			>back</button
		>
		<button
			on:click={next}
			class="bg-green-500 hover:bg-green-600 dark:text-white font-bold py-2 px-4 text-2xl basis-1/2"
			>next</button
		>
	</div>
</div>
